package proxy

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/alitrack/quack-proxy/internal/config"
	"github.com/alitrack/quack-proxy/internal/logger"
	"github.com/alitrack/quack-proxy/internal/supervisor"
)

func newTestLogger() *logger.Logger {
	log, err := logger.New(logger.Config{Level: logger.LevelQuiet})
	if err != nil {
		panic(err)
	}
	return log
}

func TestGenerateHAProxy(t *testing.T) {
	tmp := t.TempDir()
	dbPath := filepath.Join(tmp, "test.db")
	os.WriteFile(dbPath, []byte{}, 0644)

	cfg := &config.Config{
		Listener: config.ListenerConfig{
			BindHost:  "0.0.0.0",
			PortStart: 9491,
		},
		Shards: []config.ShardConfig{
			{Name: "shard1", Database: dbPath, Port: 9491},
			{Name: "shard2", Database: dbPath, Port: 9492},
		},
		Proxy: &config.ProxyConfig{
			Enabled:  true,
			BindPort: 9490,
			Mode:     "roundrobin",
		},
	}

	sup := supervisor.New(cfg, newTestLogger())

	// Manually inject "healthy" shards so GenerateHAProxy picks them up
	// (a fresh supervisor has no running processes, so Status() returns empty)
	sup.ManualSetShard("shard1", supervisor.ShardProcess{
		Config: cfg.Shards[0],
		Status: "healthy",
	})
	sup.ManualSetShard("shard2", supervisor.ShardProcess{
		Config: cfg.Shards[1],
		Status: "healthy",
	})

	outputPath := filepath.Join(tmp, "haproxy.cfg")
	if err := GenerateHAProxy(cfg, sup, outputPath); err != nil {
		t.Fatalf("GenerateHAProxy(): %v", err)
	}

	data, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("read output: %v", err)
	}

	content := string(data)

	checks := []string{
		"frontend quack_frontend",
		"bind *:9490",
		"backend quack_backend",
		"balance roundrobin",
		"server shard1 0.0.0.0:9491",
		"server shard2 0.0.0.0:9492",
		"mode tcp",
		"timeout connect 5s",
		"# Generated by quack-proxy",
	}

	for _, check := range checks {
		if !strings.Contains(content, check) {
			t.Errorf("output missing %q", check)
		}
	}
}

func TestGenerateHAProxyLeastConn(t *testing.T) {
	tmp := t.TempDir()
	dbPath := filepath.Join(tmp, "test.db")
	os.WriteFile(dbPath, []byte{}, 0644)

	cfg := &config.Config{
		Listener: config.ListenerConfig{BindHost: "localhost"},
		Shards: []config.ShardConfig{
			{Name: "s1", Database: dbPath, Port: 9491},
		},
		Proxy: &config.ProxyConfig{
			Enabled:  true,
			BindPort: 9490,
			Mode:     "leastconn",
		},
	}

	sup := supervisor.New(cfg, newTestLogger())
	sup.ManualSetShard("s1", supervisor.ShardProcess{
		Config: cfg.Shards[0],
		Status: "healthy",
	})

	outputPath := filepath.Join(tmp, "haproxy.cfg")
	if err := GenerateHAProxy(cfg, sup, outputPath); err != nil {
		t.Fatalf("GenerateHAProxy(): %v", err)
	}

	data, _ := os.ReadFile(outputPath)
	if !strings.Contains(string(data), "balance leastconn") {
		t.Error("expected leastconn balance mode")
	}
}

func TestGenerateHAProxyOnlyHealthyShards(t *testing.T) {
	tmp := t.TempDir()
	dbPath := filepath.Join(tmp, "test.db")
	os.WriteFile(dbPath, []byte{}, 0644)

	cfg := &config.Config{
		Listener: config.ListenerConfig{BindHost: "0.0.0.0"},
		Shards: []config.ShardConfig{
			{Name: "healthy", Database: dbPath, Port: 9491},
			{Name: "unhealthy", Database: dbPath, Port: 9492},
		},
		Proxy: &config.ProxyConfig{Enabled: true, BindPort: 9490},
	}

	sup := supervisor.New(cfg, newTestLogger())
	sup.ManualSetShard("healthy", supervisor.ShardProcess{
		Config: cfg.Shards[0],
		Status: "healthy",
	})
	sup.ManualSetShard("unhealthy", supervisor.ShardProcess{
		Config: cfg.Shards[1],
		Status: "unhealthy",
	})

	outputPath := filepath.Join(tmp, "haproxy.cfg")
	GenerateHAProxy(cfg, sup, outputPath)

	data, _ := os.ReadFile(outputPath)
	content := string(data)

	if strings.Contains(content, "server unhealthy") {
		t.Error("unhealthy shard should NOT appear in HAProxy config")
	}
	if !strings.Contains(content, "server healthy") {
		t.Error("healthy shard SHOULD appear in HAProxy config")
	}
}
