// Package proxy generates HAProxy/Nginx configuration for the Quack cluster.
package proxy

import (
	"fmt"
	"os"
	"strings"

	"github.com/alitrack/quack-proxy/internal/config"
	"github.com/alitrack/quack-proxy/internal/supervisor"
)

// GenerateHAProxy writes an HAProxy configuration file for the current cluster state.
func GenerateHAProxy(cfg *config.Config, sup *supervisor.Supervisor, outputPath string) error {
	if cfg.Proxy == nil || !cfg.Proxy.Enabled {
		return fmt.Errorf("proxy generation is not enabled in config")
	}

	shards := sup.Status()
	healthyShards := make([]supervisor.ShardProcess, 0)
	for _, s := range shards {
		if s.Status == "healthy" {
			healthyShards = append(healthyShards, s)
		}
	}

	var sb strings.Builder
	sb.WriteString("# Generated by quack-proxy — DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("# Generated at: %s\n\n", "auto")) // time.Now would require import
	sb.WriteString("global\n")
	sb.WriteString("    log /dev/log local0\n")
	sb.WriteString("    maxconn 4096\n")
	sb.WriteString("    daemon\n\n")
	sb.WriteString("defaults\n")
	sb.WriteString("    mode tcp\n")
	sb.WriteString("    timeout connect 5s\n")
	sb.WriteString("    timeout client 30s\n")
	sb.WriteString("    timeout server 30s\n\n")
	sb.WriteString(fmt.Sprintf("frontend quack_frontend\n"))
	sb.WriteString(fmt.Sprintf("    bind *:%d\n", cfg.Proxy.BindPort))
	sb.WriteString("    default_backend quack_backend\n\n")
	sb.WriteString("backend quack_backend\n")
	if cfg.Proxy.Mode == "leastconn" {
		sb.WriteString("    balance leastconn\n")
	} else {
		sb.WriteString("    balance roundrobin\n")
	}

	for _, s := range healthyShards {
		sb.WriteString(fmt.Sprintf("    server %s %s:%d check inter 5s\n",
			s.Config.Name, cfg.Listener.BindHost, s.Config.Port))
	}

	return os.WriteFile(outputPath, []byte(sb.String()), 0644)
}
